export const WAITLIST_USER_TYPES = ['student', 'therapist'] as const

export type WaitlistUserType = (typeof WAITLIST_USER_TYPES)[number]

export const UK_UNIVERSITIES = [
  'Aberystwyth University',
  'Anglia Ruskin University',
  'Aston University',
  'Bangor University',
  'Bath Spa University',
  'Birkbeck, University of London',
  'Birmingham City University',
  'Bournemouth University',
  'Brunel University London',
  'Buckinghamshire New University',
  'Canterbury Christ Church University',
  'Cardiff Metropolitan University',
  'Cardiff University',
  'City St George’s, University of London',
  'Coventry University',
  'Cranfield University',
  'De Montfort University',
  'Durham University',
  'Edge Hill University',
  'Edinburgh Napier University',
  'Falmouth University',
  'Glasgow Caledonian University',
  'Goldsmiths, University of London',
  'Harper Adams University',
  'Heriot-Watt University',
  'Imperial College London',
  'Keele University',
  'Kingston University',
  'Lancaster University',
  'Leeds Beckett University',
  'Liverpool Hope University',
  'Liverpool John Moores University',
  'London Metropolitan University',
  'London School of Economics and Political Science',
  'London South Bank University',
  'Loughborough University',
  'Manchester Metropolitan University',
  'Middlesex University',
  'Newcastle University',
  'Northumbria University',
  'Nottingham Trent University',
  'Oxford Brookes University',
  'Queen Margaret University',
  'Queen Mary University of London',
  'Queen’s University Belfast',
  'Robert Gordon University',
  'Royal Agricultural University',
  'Royal Central School of Speech and Drama',
  'Royal College of Art',
  'Royal College of Music',
  'Royal Holloway, University of London',
  'Royal Northern College of Music',
  'Royal Veterinary College',
  'Sheffield Hallam University',
  'SOAS University of London',
  'Solent University',
  'St Mary’s University, Twickenham',
  'Staffordshire University',
  'Swansea University',
  'Teesside University',
  'The Open University',
  'University College Birmingham',
  'University College London',
  'University for the Creative Arts',
  'University of Aberdeen',
  'University of Bath',
  'University of Bedfordshire',
  'University of Birmingham',
  'University of Bolton',
  'University of Bradford',
  'University of Brighton',
  'University of Bristol',
  'University of Buckingham',
  'University of Cambridge',
  'University of Central Lancashire',
  'University of Chester',
  'University of Chichester',
  'University of Cumbria',
  'University of Derby',
  'University of Dundee',
  'University of East Anglia',
  'University of East London',
  'University of Edinburgh',
  'University of Essex',
  'University of Exeter',
  'University of Glasgow',
  'University of Gloucestershire',
  'University of Greenwich',
  'University of Hertfordshire',
  'University of Huddersfield',
  'University of Hull',
  'University of Kent',
  'University of Leeds',
  'University of Leicester',
  'University of Lincoln',
  'University of Liverpool',
  'University of Manchester',
  'University of Northampton',
  'University of Nottingham',
  'University of Oxford',
  'University of Plymouth',
  'University of Portsmouth',
  'University of Reading',
  'University of Roehampton',
  'University of Salford',
  'University of Sheffield',
  'University of South Wales',
  'University of Southampton',
  'University of St Andrews',
  'University of Stirling',
  'University of Strathclyde',
  'University of Suffolk',
  'University of Sunderland',
  'University of Surrey',
  'University of Sussex',
  'University of the Arts London',
  'University of the Highlands and Islands',
  'University of the West of England',
  'University of Warwick',
  'University of West London',
  'University of Westminster',
  'University of Winchester',
  'University of Wolverhampton',
  'University of Worcester',
  'University of York',
  'Other',
] as const

export const HOW_HEARD_OPTIONS = [
  { value: 'tik_tok', label: 'Tik tok' },
  { value: 'instagram', label: 'Instagram' },
  { value: 'linked_in', label: 'Linked in' },
  { value: 'word_of_mouth', label: 'Word of mouth' },
  { value: 'blog', label: 'Blog' },
  { value: 'google_search', label: 'Google search' },
  { value: 'university', label: 'University' },
  { value: 'other', label: 'Other' },
] as const

export const ACCREDITATION_BODIES = [
  { value: 'BACP', label: 'BACP' },
  { value: 'UKCP', label: 'UKCP' },
  { value: 'NCPS', label: 'NCPS' },
  { value: 'BABCP', label: 'BABCP' },
  { value: 'BPS', label: 'BPS' },
  { value: 'COSCA', label: 'COSCA' },
  { value: 'other', label: 'Other' },
] as const

export const HOW_HEARD_VALUES = HOW_HEARD_OPTIONS.map((option) => option.value)

export const ACCREDITATION_BODY_VALUES = ACCREDITATION_BODIES.map((option) => option.value)
